version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes: 
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  backend_user:
    build: ./backend-USER
    container_name: backend_d
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend-USER:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    
volumes:
  mongo-data:



      